<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Specific Complaint Report</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #0f172a;
            font-size: 12px;
            line-height: 1.5;
        }

        .header {
            border-bottom: 3px solid #1e3a8a;
            padding-bottom: 12px;
            margin-bottom: 18px;
        }

        .system-title {
            margin: 0;
            color: #1e3a8a;
            font-size: 13px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 0.04em;
        }

        .title {
            margin: 4px 0 0;
            color: #0f172a;
            font-size: 22px;
            font-weight: bold;
        }

        .subtitle {
            margin-top: 4px;
            color: #475569;
            font-size: 11px;
        }

        .meta {
            margin-top: 10px;
            font-size: 10px;
            color: #475569;
        }

        .notice {
            margin-bottom: 16px;
            border: 1px solid #bfdbfe;
            background: #eff6ff;
            color: #1e3a8a;
            padding: 9px 10px;
            font-size: 10px;
            font-weight: bold;
        }

        .section {
            margin-top: 16px;
        }

        .section-title {
            background: #1e3a8a;
            color: #ffffff;
            font-weight: bold;
            padding: 8px 10px;
            margin: 0;
            font-size: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            page-break-inside: auto;
        }

        tr {
            page-break-inside: avoid;
        }

        td,
        th {
            border: 1px solid #cbd5e1;
            padding: 8px;
            vertical-align: top;
        }

        th {
            background: #f8fafc;
            color: #334155;
            text-align: left;
            font-weight: bold;
            font-size: 10px;
        }

        .label {
            width: 30%;
            background: #f8fafc;
            font-weight: bold;
            color: #334155;
        }

        .value {
            color: #0f172a;
        }

        .wide-text {
            min-height: 42px;
            white-space: pre-line;
        }

        .muted {
            color: #64748b;
        }

        .footer {
            margin-top: 28px;
            border-top: 1px solid #cbd5e1;
            padding-top: 10px;
            font-size: 10px;
            color: #64748b;
        }
    </style>
</head>

@php
    $complaintReport = $complaintReport ?? [];
    $proofRecords = $proofRecords ?? collect();
    $generatedBy = $generatedBy ?? 'System';
    $generatedAt = $generatedAt ?? now();

    $value = function (string $key, string $default = '—') use ($complaintReport) {
        $rawValue = $complaintReport[$key] ?? null;

        if ($rawValue === null) {
            return $default;
        }

        $text = trim((string) $rawValue);

        return $text !== '' ? $text : $default;
    };
@endphp

<body>
    <div class="header">
        <p class="system-title">TabangNow / DaoSystem</p>

        <p class="title">Specific Complaint Report</p>

        <p class="subtitle">
            Resident Complaint Documentation — Dao, Capiz
        </p>

        <div class="meta">
            Generated by: {{ $generatedBy }}<br>
            Generated at: {{ \Illuminate\Support\Carbon::parse($generatedAt)->format('M d, Y h:i A') }}
        </div>
    </div>

    <div class="notice">
        This report contains only the selected resident complaint and its directly related records. Other complaints or incidents are excluded.
    </div>

    <div class="section">
        <p class="section-title">Complaint Details</p>

        <table>
            <tr>
                <td class="label">Complaint Code</td>
                <td class="value">{{ $value('code') }}</td>
            </tr>

            <tr>
                <td class="label">Title / Subject</td>
                <td class="value">{{ $value('title') }}</td>
            </tr>

            <tr>
                <td class="label">Complainant</td>
                <td class="value">{{ $value('complainant') }}</td>
            </tr>

            <tr>
                <td class="label">Address / Location</td>
                <td class="value">{{ $value('address') }}</td>
            </tr>

            <tr>
                <td class="label">Status</td>
                <td class="value">{{ $value('status') }}</td>
            </tr>

            <tr>
                <td class="label">Complaint Date & Time</td>
                <td class="value">{{ $value('date_time') }}</td>
            </tr>

            <tr>
                <td class="label">Created At</td>
                <td class="value">{{ $value('created_at') }}</td>
            </tr>

            <tr>
                <td class="label">Last Updated</td>
                <td class="value">{{ $value('updated_at') }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <p class="section-title">Complaint Narrative / Details</p>

        <table>
            <tr>
                <td class="wide-text">{{ $value('description') }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <p class="section-title">Proofs / Attachments</p>

        @if ($proofRecords->count())
            <table>
                <thead>
                    <tr>
                        <th>File Name</th>
                        <th>Type</th>
                        <th>Size</th>
                        <th>Uploaded At</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($proofRecords as $proof)
                        <tr>
                            <td>{{ $proof['file_name'] ?? 'Proof file' }}</td>
                            <td>{{ $proof['file_type'] ?? '—' }}</td>
                            <td>{{ $proof['file_size'] ?? '—' }}</td>
                            <td>{{ $proof['uploaded_at'] ?? '—' }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <table>
                <tr>
                    <td class="muted">
                        No proof or attachment records found for this complaint.
                    </td>
                </tr>
            </table>
        @endif
    </div>

    <div class="footer">
        This report is generated from TabangNow / DaoSystem records. It is intended for barangay complaint documentation and monitoring.
    </div>
</body>
</html>