<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Incident Report</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #0f172a;
            font-size: 12px;
            line-height: 1.5;
        }

        .header {
            border-bottom: 2px solid #1e3a8a;
            padding-bottom: 12px;
            margin-bottom: 18px;
        }

        .system-title {
            margin: 0;
            color: #1e3a8a;
            font-size: 12px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 0.04em;
        }

        .title {
            font-size: 22px;
            font-weight: bold;
            color: #1e3a8a;
            margin: 0;
        }

        .subtitle {
            margin-top: 4px;
            color: #475569;
        }

        .meta {
            margin-top: 10px;
            font-size: 11px;
            color: #475569;
        }

        .section {
            margin-top: 18px;
        }

        .section-title {
            background: #eff6ff;
            border: 1px solid #bfdbfe;
            color: #1e3a8a;
            font-weight: bold;
            padding: 8px 10px;
            margin-bottom: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        td,
        th {
            border: 1px solid #cbd5e1;
            padding: 8px;
            vertical-align: top;
        }

        th {
            background: #f8fafc;
            text-align: left;
            font-weight: bold;
        }

        .label {
            width: 28%;
            background: #f8fafc;
            font-weight: bold;
            color: #334155;
        }

        .muted {
            color: #64748b;
        }

        .footer {
            margin-top: 28px;
            border-top: 1px solid #cbd5e1;
            padding-top: 10px;
            font-size: 10px;
            color: #64748b;
        }
    </style>
</head>
<body>
    <div class="header">
        <p class="system-title">TabangNow / DaoSystem</p>
        <p class="title">Incident Report</p>
        <p class="subtitle">
            Barangay Incident Documentation — Dao, Capiz
        </p>

        <div class="meta">
            Generated by: {{ $generatedBy }}<br>
            Generated at: {{ $generatedAt->format('M d, Y h:i A') }}
        </div>
    </div>

    <div class="section">
        <div class="section-title">Incident Details</div>

        <table>
            <tr>
                <td class="label">Incident Code</td>
                <td>{{ $incidentReport['code'] }}</td>
            </tr>

            <tr>
                <td class="label">Title</td>
                <td>{{ $incidentReport['title'] }}</td>
            </tr>

            <tr>
                <td class="label">Incident Category</td>
                <td>{{ $incidentReport['category'] }}</td>
            </tr>

            <tr>
                <td class="label">Barangay Area</td>
                <td>{{ $incidentReport['barangay'] }}</td>
            </tr>

            <tr>
                <td class="label">Status</td>
                <td>{{ $incidentReport['status'] }}</td>
            </tr>

            <tr>
                <td class="label">Priority / Severity</td>
                <td>{{ $incidentReport['priority'] }}</td>
            </tr>

            <tr>
                <td class="label">Incident Date & Time</td>
                <td>{{ $incidentReport['date_time'] }}</td>
            </tr>

            <tr>
                <td class="label">Created At</td>
                <td>{{ $incidentReport['created_at'] }}</td>
            </tr>

            <tr>
                <td class="label">Last Updated</td>
                <td>{{ $incidentReport['updated_at'] }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Reporting, Assignment & Location</div>

        <table>
            <tr>
                <td class="label">Reported By</td>
                <td>{{ $incidentReport['reporter'] }}</td>
            </tr>

            <tr>
                <td class="label">Reported At</td>
                <td>{{ $incidentReport['reported_at'] }}</td>
            </tr>

            <tr>
                <td class="label">Assigned Responder</td>
                <td>{{ $incidentReport['assigned_responder'] }}</td>
            </tr>

            <tr>
                <td class="label">Location</td>
                <td>{{ $incidentReport['location_name'] }}</td>
            </tr>

            <tr>
                <td class="label">GPS Coordinates</td>
                <td>
                    {{ $incidentReport['latitude'] }},
                    {{ $incidentReport['longitude'] }}
                </td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Narrative / Description</div>

        <table>
            <tr>
                <td>{{ $incidentReport['description'] }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Persons Involved</div>

        <table>
            <tr>
                <td>{{ $incidentReport['persons_involved'] }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Related Case Records</div>

        @if ($relatedCases->count())
            <table>
                <thead>
                    <tr>
                        <th>Case No.</th>
                        <th>Subject</th>
                        <th>Type</th>
                        <th>Status</th>
                        <th>Handled By</th>
                        <th>Hearing</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($relatedCases as $case)
                        <tr>
                            <td>{{ $case['case_number'] }}</td>
                            <td>{{ $case['subject_name'] }}</td>
                            <td>{{ $case['case_type'] }}</td>
                            <td>{{ $case['status'] }}</td>
                            <td>{{ $case['handled_by'] }}</td>
                            <td>{{ $case['hearing_date'] }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <table>
                <tr>
                    <td class="muted">No related case record found for this incident.</td>
                </tr>
            </table>
        @endif
    </div>

    <div class="section">
        <div class="section-title">Evidence / Attachments</div>

        @if ($evidenceRecords->count())
            <table>
                <thead>
                    <tr>
                        <th>File Name</th>
                        <th>Type</th>
                        <th>Size</th>
                        <th>Uploaded At</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($evidenceRecords as $evidence)
                        <tr>
                            <td>{{ $evidence['file_name'] }}</td>
                            <td>{{ $evidence['file_type'] }}</td>
                            <td>{{ $evidence['file_size'] }}</td>
                            <td>{{ $evidence['uploaded_at'] }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <table>
                <tr>
                    <td class="muted">No evidence or attachment records found for this incident.</td>
                </tr>
            </table>
        @endif
    </div>

    <div class="section">
        <div class="section-title">Tanod Task / Response Records</div>

        @if ($tanodTaskRecords->count())
            @foreach ($tanodTaskRecords as $task)
                <table style="margin-bottom: 10px;">
                    <tr>
                        <td class="label">Task</td>
                        <td>{{ $task['title'] }}</td>
                    </tr>

                    <tr>
                        <td class="label">Status</td>
                        <td>{{ $task['status'] }}</td>
                    </tr>

                    <tr>
                        <td class="label">Created At</td>
                        <td>{{ $task['created_at'] }}</td>
                    </tr>
                </table>

                @if ($task['responses']->count())
                    <table style="margin-bottom: 14px;">
                        <thead>
                            <tr>
                                <th>Responder</th>
                                <th>Status</th>
                                <th>Note</th>
                                <th>Responded At</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach ($task['responses'] as $response)
                                <tr>
                                    <td>{{ $response['responder_name'] }}</td>
                                    <td>{{ $response['response_status'] }}</td>
                                    <td>{{ $response['response_note'] }}</td>
                                    <td>{{ $response['responded_at'] }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                @endif
            @endforeach
        @else
            <table>
                <tr>
                    <td class="muted">No tanod task records found for this incident.</td>
                </tr>
            </table>
        @endif
    </div>

    <div class="footer">
        This report is generated from TabangNow system records. It contains only the selected incident and its directly related records.
    </div>
</body>
</html>