<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Barangay Report - {{ $periodLabel }}</title>

    <style>
        * {
            box-sizing: border-box;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            color: #111827;
            font-size: 11px;
            line-height: 1.45;
            margin: 0;
            padding: 0;
        }

        .page {
            padding: 28px;
        }

        .header {
            border-bottom: 2px solid #1e3a8a;
            padding-bottom: 14px;
            margin-bottom: 18px;
        }

        .header-title {
            font-size: 18px;
            font-weight: bold;
            color: #111827;
            margin: 0;
        }

        .header-subtitle {
            margin-top: 4px;
            color: #4b5563;
            font-size: 11px;
        }

        .meta-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 12px;
        }

        .meta-table td {
            padding: 3px 0;
            font-size: 10px;
            color: #374151;
        }

        .section {
            margin-top: 18px;
        }

        .section-title {
            font-size: 13px;
            font-weight: bold;
            margin-bottom: 8px;
            color: #111827;
        }

        .summary-grid {
            width: 100%;
            border-collapse: collapse;
        }

        .summary-grid td {
            width: 20%;
            border: 1px solid #d1d5db;
            padding: 10px;
            vertical-align: top;
        }

        .summary-label {
            font-size: 9px;
            color: #6b7280;
            text-transform: uppercase;
            font-weight: bold;
            margin-bottom: 5px;
        }

        .summary-value {
            font-size: 18px;
            font-weight: bold;
            color: #111827;
        }

        table.data-table {
            width: 100%;
            border-collapse: collapse;
        }

        table.data-table th {
            background: #f3f4f6;
            color: #374151;
            font-size: 9px;
            text-transform: uppercase;
            text-align: left;
            border: 1px solid #d1d5db;
            padding: 6px;
        }

        table.data-table td {
            border: 1px solid #d1d5db;
            padding: 6px;
            vertical-align: top;
        }

        .empty {
            border: 1px dashed #d1d5db;
            background: #f9fafb;
            padding: 14px;
            text-align: center;
            color: #6b7280;
        }

        .two-column {
            width: 100%;
            border-collapse: collapse;
        }

        .two-column td {
            width: 50%;
            vertical-align: top;
            padding-right: 10px;
        }

        .footer {
            margin-top: 24px;
            padding-top: 12px;
            border-top: 1px solid #d1d5db;
            font-size: 10px;
            color: #4b5563;
        }

        .signature-table {
            width: 100%;
            margin-top: 35px;
            border-collapse: collapse;
        }

        .signature-table td {
            width: 50%;
            text-align: center;
            padding-top: 28px;
        }

        .signature-line {
            border-top: 1px solid #111827;
            width: 70%;
            margin: 0 auto 5px;
        }
    </style>
</head>

<body>
    <div class="page">
        <div class="header">
            <p class="header-title">Reports & Analytics</p>

            <div class="header-subtitle">
                BrgySafe - Dao, Capiz Community Safety Incident System
            </div>

            <table class="meta-table">
                <tr>
                    <td>
                        <strong>Report Period:</strong> {{ $periodLabel }}
                    </td>

                    <td>
                        <strong>Generated:</strong> {{ $generatedAt->format('F d, Y h:i A') }}
                    </td>
                </tr>

                <tr>
                    <td>
                        <strong>Coverage:</strong> {{ $startDate->format('F d, Y') }} to {{ $endDate->format('F d, Y') }}
                    </td>

                    <td>
                        <strong>Generated By:</strong> {{ $generatedBy }}
                    </td>
                </tr>
            </table>
        </div>

        <div class="section">
            <div class="section-title">Summary</div>

            <table class="summary-grid">
                <tr>
                    <td>
                        <div class="summary-label">Total Incidents</div>
                        <div class="summary-value">{{ $totalIncidents }}</div>
                    </td>

                    <td>
                        <div class="summary-label">Active / Pending</div>
                        <div class="summary-value">{{ $activeIncidents }}</div>
                    </td>

                    <td>
                        <div class="summary-label">Resolved</div>
                        <div class="summary-value">{{ $resolvedIncidents }}</div>
                    </td>

                    <td>
                        <div class="summary-label">Cases Filed</div>
                        <div class="summary-value">{{ $casesFiled }}</div>
                    </td>

                    <td>
                        <div class="summary-label">Emergency Logs</div>
                        <div class="summary-value">{{ $emergencyLogs }}</div>
                    </td>
                </tr>
            </table>
        </div>

        <div class="section">
            <div class="section-title">Records Breakdown</div>

            @if (count($records))
                <table class="data-table">
                    <thead>
                        <tr>
                            <th style="width: 16%;">Category</th>
                            <th style="width: 44%;">Title / Details</th>
                            <th style="width: 20%;">Type</th>
                            <th style="width: 20%;">Date & Time</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach ($records as $record)
                            <tr>
                                <td>{{ $record['category'] }}</td>
                                <td>{{ $record['title'] }}</td>
                                <td>{{ $record['type'] }}</td>
                                <td>{{ $record['datetime'] }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
                <div class="empty">
                    No records found for {{ strtolower($periodLabel) }}.
                </div>
            @endif
        </div>

        <div class="section">
            <table class="two-column">
                <tr>
                    <td>
                        <div class="section-title">Incident Status Summary</div>

                        @if (count($statusSummary))
                            <table class="data-table">
                                <thead>
                                    <tr>
                                        <th>Status</th>
                                        <th>Total</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach ($statusSummary as $item)
                                        <tr>
                                            <td>{{ $item['label'] }}</td>
                                            <td>{{ $item['total'] }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @else
                            <div class="empty">No status data available.</div>
                        @endif
                    </td>

                    <td>
                        <div class="section-title">Severity Summary</div>

                        @if (count($severitySummary))
                            <table class="data-table">
                                <thead>
                                    <tr>
                                        <th>Severity</th>
                                        <th>Total</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach ($severitySummary as $item)
                                        <tr>
                                            <td>{{ $item['label'] }}</td>
                                            <td>{{ $item['total'] }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @else
                            <div class="empty">No severity data available.</div>
                        @endif
                    </td>
                </tr>
            </table>
        </div>

        <div class="section">
            <div class="section-title">Barangay Area Summary</div>

            @if (count($barangaySummary))
                <table class="data-table">
                    <thead>
                        <tr>
                            <th>Barangay</th>
                            <th>Total Incidents</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach ($barangaySummary as $item)
                            <tr>
                                <td>{{ $item['label'] }}</td>
                                <td>{{ $item['total'] }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
                <div class="empty">
                    No barangay area data available.
                </div>
            @endif
        </div>

        <div class="section">
            <div class="section-title">Tanod Response Summary</div>

            @if (count($tanodSummary))
                <table class="data-table">
                    <thead>
                        <tr>
                            <th>Tanod</th>
                            <th>Badge</th>
                            <th>Assigned</th>
                            <th>Resolved</th>
                            <th>Pending</th>
                            <th>Last Update</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach ($tanodSummary as $tanod)
                            <tr>
                                <td>{{ $tanod['name'] }}</td>
                                <td>{{ $tanod['badge'] }}</td>
                                <td>{{ $tanod['assigned'] }}</td>
                                <td>{{ $tanod['resolved'] }}</td>
                                <td>{{ $tanod['pending'] }}</td>
                                <td>{{ $tanod['last_update'] }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
                <div class="empty">
                    No tanod assignments recorded for this period.
                </div>
            @endif
        </div>

        <table class="signature-table">
            <tr>
                <td>
                    <div class="signature-line"></div>
                    Prepared by
                </td>

                <td>
                    <div class="signature-line"></div>
                    Reviewed by
                </td>
            </tr>
        </table>

        <div class="footer">
            This report was generated by BrgySafe for barangay incident monitoring and administrative documentation.
        </div>
    </div>
</body>
</html>