<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SOS / Distress Signal Report</title>

    <style>
        @page {
            margin: 28px 32px 34px;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            color: #0f172a;
            font-size: 11px;
            line-height: 1.45;
        }

        .header {
            border-bottom: 3px solid #b91c1c;
            padding-bottom: 12px;
            margin-bottom: 16px;
        }

        .system-title {
            margin: 0;
            color: #1e3a8a;
            font-size: 12px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 0.04em;
        }

        .title {
            margin: 4px 0 0;
            color: #0f172a;
            font-size: 21px;
            font-weight: bold;
        }

        .subtitle {
            margin-top: 4px;
            color: #475569;
            font-size: 10px;
        }

        .meta {
            margin-top: 9px;
            color: #64748b;
            font-size: 9px;
        }

        .notice {
            border: 1px solid #fecaca;
            background: #fef2f2;
            color: #991b1b;
            padding: 9px 10px;
            margin-bottom: 15px;
            font-size: 9px;
            font-weight: bold;
        }

        .section {
            margin-top: 14px;
            page-break-inside: avoid;
        }

        .section-title {
            margin: 0;
            background: #1e3a8a;
            color: #ffffff;
            padding: 7px 9px;
            font-size: 11px;
            font-weight: bold;
        }

        .section-title.emergency {
            background: #b91c1c;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        tr {
            page-break-inside: avoid;
        }

        td,
        th {
            border: 1px solid #cbd5e1;
            padding: 7px 8px;
            vertical-align: top;
        }

        .label {
            width: 31%;
            background: #f8fafc;
            color: #334155;
            font-weight: bold;
        }

        .value {
            color: #0f172a;
        }

        .narrative {
            min-height: 70px;
            white-space: pre-line;
            font-size: 11px;
            line-height: 1.55;
        }

        .status {
            font-weight: bold;
            text-transform: uppercase;
        }

        .footer {
            margin-top: 24px;
            padding-top: 9px;
            border-top: 1px solid #cbd5e1;
            color: #64748b;
            font-size: 9px;
        }
    </style>
</head>
<body>
    @php
        $report = $sosReport ?? [];
        $generatedAtText = $generatedAt instanceof \DateTimeInterface
            ? $generatedAt->format('M d, Y h:i A')
            : (string) $generatedAt;
        $value = static function (string $key, string $fallback = '—') use ($report): string {
            $raw = $report[$key] ?? null;
            $text = trim((string) ($raw ?? ''));

            return $text !== '' ? $text : $fallback;
        };
    @endphp

    <div class="header">
        <p class="system-title">TabangNow / DaoSystem</p>
        <p class="title">SOS / Distress Signal Report</p>
        <p class="subtitle">
            Emergency Response Documentation — Dao, Capiz
        </p>

        <div class="meta">
            Generated by: {{ $generatedBy ?? 'System' }}<br>
            Generated at: {{ $generatedAtText }}
        </div>
    </div>

    <div class="notice">
        This document contains one selected SOS / Distress Signal record and its recorded response timeline.
    </div>

    <div class="section">
        <p class="section-title emergency">Emergency Summary</p>
        <table>
            <tr>
                <td class="label">Alert Code</td>
                <td class="value"><strong>{{ $value('alert_code') }}</strong></td>
            </tr>
            <tr>
                <td class="label">Current Status</td>
                <td class="value status">{{ $value('status') }}</td>
            </tr>
            <tr>
                <td class="label">Triggered At</td>
                <td class="value">{{ $value('triggered_at') }}</td>
            </tr>
            <tr>
                <td class="label">Source</td>
                <td class="value">{{ $value('source') }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <p class="section-title">Reporter & Contact</p>
        <table>
            <tr>
                <td class="label">Linked TabangNow User</td>
                <td class="value">{{ $value('reporter_name') }}</td>
            </tr>
            <tr>
                <td class="label">Role / Identity</td>
                <td class="value">{{ $value('reporter_role') }}</td>
            </tr>
            <tr>
                <td class="label">Mobile Number</td>
                <td class="value">{{ $value('contact_number') }}</td>
            </tr>
            <tr>
                <td class="label">Registered Address</td>
                <td class="value">{{ $value('registered_address') }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <p class="section-title emergency">Emergency Narrative</p>
        <table>
            <tr>
                <td class="narrative">{{ $value('emergency_details', 'No emergency description available.') }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <p class="section-title">Location Information</p>
        <table>
            <tr>
                <td class="label">Location Source</td>
                <td class="value">{{ $value('location_source') }}</td>
            </tr>
            <tr>
                <td class="label">Latitude</td>
                <td class="value">{{ $value('latitude') }}</td>
            </tr>
            <tr>
                <td class="label">Longitude</td>
                <td class="value">{{ $value('longitude') }}</td>
            </tr>
            <tr>
                <td class="label">Reported Accuracy</td>
                <td class="value">{{ $value('accuracy') }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <p class="section-title">Response Timeline</p>
        <table>
            <tr>
                <td class="label">Acknowledged At</td>
                <td class="value">{{ $value('acknowledged_at') }}</td>
            </tr>
            <tr>
                <td class="label">Acknowledged By</td>
                <td class="value">{{ $value('acknowledged_by') }}</td>
            </tr>
            <tr>
                <td class="label">Resolved At</td>
                <td class="value">{{ $value('resolved_at') }}</td>
            </tr>
            <tr>
                <td class="label">Resolved By</td>
                <td class="value">{{ $value('resolved_by') }}</td>
            </tr>
            <tr>
                <td class="label">Record Last Updated</td>
                <td class="value">{{ $value('updated_at') }}</td>
            </tr>
        </table>
    </div>

    <div class="footer">
        Generated from the TabangNow SOS / Distress Signal responder record.
        Location coordinates and response timestamps reflect the data stored by the system at generation time.
    </div>
</body>
</html>